# Generated by Django 4.2.7 on 2025-12-07 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('business_short_code', models.CharField(max_length=20)),
                ('passkey', models.CharField(max_length=255)),
                ('api_base_url', models.URLField(default='https://sandbox.safaricom.co.ke')),
                ('callback_url', models.URLField()),
                ('timeout_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('max_requests_per_minute', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
            },
        ),
        migrations.CreateModel(
            name='MpesaWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('body', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Webhook Log',
                'verbose_name_plural': 'M-Pesa Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('stk_push', 'STK Push'), ('b2c', 'Business to Customer'), ('b2b', 'Business to Business'), ('c2b', 'Customer to Business'), ('account_balance', 'Account Balance'), ('reversal', 'Reversal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_desc', models.CharField(blank=True, max_length=255)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.mpesaconfiguration')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True)),
                ('reversal_id', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_refunds', to='orders.orderreturn')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.mpesatransaction')),
                ('reversal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_refunds', to='payments.mpesatransaction')),
            ],
            options={
                'verbose_name': 'M-Pesa Refund',
                'verbose_name_plural': 'M-Pesa Refunds',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payment_methods', to='customers.customer')),
            ],
            options={
                'verbose_name': 'M-Pesa Payment Method',
                'verbose_name_plural': 'M-Pesa Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('callback_type', models.CharField(choices=[('stk_callback', 'STK Callback'), ('validation', 'Validation'), ('confirmation', 'Confirmation'), ('timeout', 'Timeout')], max_length=20)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='payments.mpesatransaction')),
            ],
            options={
                'verbose_name': 'M-Pesa Callback',
                'verbose_name_plural': 'M-Pesa Callbacks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='payments.mpesaconfiguration')),
            ],
            options={
                'verbose_name': 'M-Pesa Access Token',
                'verbose_name_plural': 'M-Pesa Access Tokens',
            },
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['merchant_request_id'], name='payments_mp_merchan_da2348_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='payments_mp_mpesa_r_3e414a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone_number', 'initiated_at'], name='payments_mp_phone_n_935a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', 'initiated_at'], name='payments_mp_status_b23370_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['order', 'status'], name='payments_mp_order_i_9c7ea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mpesapaymentmethod',
            unique_together={('customer', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_7dc86e_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['is_processed', 'received_at'], name='payments_mp_is_proc_51868b_idx'),
        ),
    ]
