# Generated by Django 4.2.7 on 2025-12-07 09:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('overstock', 'Overstock'), ('reorder_point', 'Reorder Point Reached'), ('damaged', 'Damaged Stock'), ('expiring', 'Expiring Soon'), ('discrepancy', 'Stock Discrepancy')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('current_quantity', models.IntegerField()),
                ('threshold_quantity', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('count_type', models.CharField(choices=[('full', 'Full Count'), ('cycle', 'Cycle Count'), ('spot', 'Spot Check')], default='cycle', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField(help_text='Quantity from system')),
                ('counted_quantity', models.IntegerField(blank=True, help_text='Actual counted quantity', null=True)),
                ('discrepancy', models.IntegerField(default=0, help_text='Difference between expected and counted')),
                ('is_counted', models.BooleanField(default=False)),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['product__sku'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-priority', 'name'], 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehousestock',
            options={'ordering': ['warehouse', 'product'], 'verbose_name_plural': 'Warehouse Stock'},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Actual date of movement (can be backdated)'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.IntegerField(default=0, help_text='Quantity after movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.IntegerField(default=0, help_text='Quantity before movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_id',
            field=models.CharField(blank=True, help_text='ID of the referenced entity', max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, help_text='Type of reference (order, transfer, adjustment)', max_length=50),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='county',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='current_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='max_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum capacity in cubic meters', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority warehouses are checked first for stock'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='street_address',
            field=models.CharField(default='Moi Avenue, 1st Floor', max_length=200),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='town',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='damaged_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='last_counted',
            field=models.DateTimeField(blank=True, help_text='Last physical count date', null=True),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='reorder_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='reorder_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Quantity reserved for pending orders', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='zone',
            field=models.CharField(blank=True, help_text='Storage zone (e.g., Cold, Dry, Hazmat)', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase/Receiving'), ('sale', 'Sale'), ('return', 'Customer Return'), ('adjustment', 'Adjustment'), ('transfer', 'Warehouse Transfer'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('found', 'Found'), ('production', 'Production'), ('sample', 'Sample'), ('promotion', 'Promotional'), ('writeoff', 'Write-off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Positive for increases, negative for decreases'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='location',
            field=models.CharField(blank=True, help_text='Aisle-Shelf-Bin (e.g., A-12-5)', max_length=50),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'product', '-created_at'], name='inventory_s_warehou_c676a0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['warehouse', 'product'], name='inventory_w_warehou_bf2f17_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['quantity'], name='inventory_w_quantit_9423d4_idx'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorytransfer'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='stock_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorytransfer'),
        ),
        migrations.AlterUniqueTogether(
            name='transferitem',
            unique_together={('transfer', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='stockcountitem',
            unique_together={('stock_count', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='inventory_s_alert_t_692cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['warehouse', 'is_resolved'], name='inventory_s_warehou_94fcd3_idx'),
        ),
    ]
