# Generated by Django 4.2.7 on 2025-12-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(default='Kericho', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
    ]
