# Generated by Django 4.2.7 on 2025-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordernote_orderreturn_orderstatushistory_returnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MPesa', 'M-Pesa'), ('PayPal', 'PayPal'), ('OnDelivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
