# Generated by Django 4.2.7 on 2025-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa STK Push checkout request ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_transaction_id',
            field=models.IntegerField(blank=True, help_text='Reference to MpesaTransaction model', null=True),
        ),
    ]
